/** M20 使用真实 Workspace 与导航表单；选区、鼠标、输入法事件为合成事件，不替代原生候选验收。 */
import { useEffect } from "react"
import ReactDOM from "react-dom"
import { Editor } from "@tiptap/core"
import { closeHistory } from "@tiptap/pm/history"
import { NodeSelection, TextSelection } from "@tiptap/pm/state"
import { EditorProvider, useDocumentEditor } from "../src/pages/editor/components/EditorProvider.jsx"
import { EditorWorkspace } from "../src/pages/editor/components/EditorWorkspace.jsx"
import { createDocument } from "../src/pages/editor/tools/document-schema.js"
import { createExtensions } from "../src/pages/editor/tools/create-extensions.js"
import { saveLocalDocument, getLocalDocument } from "../src/pages/editor/tools/local-repository.js"
import { createPortableFile, readPortableFile, createDocumentHtml } from "../src/pages/editor/tools/file-transfer.js"
import { listNavigationTargets, captureNavigationBlockTarget, setBookmarkName, captureNavigationInsertTarget, insertTableOfContentsAtTarget,
  captureTableOfContentsTarget, refreshTableOfContents, removeTableOfContents, captureNavigationLinkTarget, applyInternalNavigationLink } from "../src/pages/editor/tools/navigation-commands.js"
import { FORMATTING_MARKS_KEY } from "../src/pages/editor/tools/formatting-marks-preferences.js"
import { TOOLBAR_MODE_KEY, TOOLBAR_MODES } from "../src/pages/editor/tools/toolbar-preferences.js"
import { removeVerificationDocuments } from "./browser-checks.js"

const assert = (condition, message) => { if (!condition) throw new Error(message) }
const delay = () => new Promise(resolve => setTimeout(resolve, 40))
const waitFor = async (read, message) => { const end = Date.now() + 10000; while (Date.now() < end) { const value = await read(); if (value) return value; await delay() } throw new Error(message) }
const visible = element => !!element?.getClientRects().length && !element.closest("[hidden]") && getComputedStyle(element).visibility !== "hidden"
const button = (host, name) => [...(host?.querySelectorAll("button") || [])].find(element => visible(element) && (element.getAttribute("aria-label") || element.textContent).replace(/\s/g, "") === name.replace(/\s/g, ""))
const dialog = name => [...document.querySelectorAll('[role="dialog"]')].find(element => visible(element) && element.querySelector(".ant-modal-title")?.textContent === name)
const content = editor => JSON.stringify(editor.getJSON())
const paragraph = value => ({ type: "paragraph", ...(value && { content: [{ type: "text", text: value }] }) })
const heading = (value, level = 2) => ({ type: "heading", attrs: { level }, content: [{ type: "text", text: value }] })
const fixture = () => ({ type: "doc", content: [paragraph("前半后半"), heading("第一章", 1), paragraph("链接文字原段"), heading("第二章", 2), heading("细节标题", 4),
  { type: "details", attrs: { summary: "折叠材料" }, content: [heading("折叠标题", 3), paragraph("书签目标正文")] }, paragraph("尾部文字")] })
const nodes = (editor, type) => { const result = []; editor.state.doc.descendants((node, pos) => { if (node.type.name === type) result.push({ node, pos }) }); return result }
const block = (editor, text) => { const item = [...nodes(editor, "paragraph"), ...nodes(editor, "heading")].find(({ node }) => node.textContent === text); assert(item, `缺少${text}`); return item }
const select = (editor, text, from = 1, to = from) => { const item = block(editor, text); editor.view.dispatch(editor.state.tr.setSelection(TextSelection.create(editor.state.doc, item.pos + from, item.pos + to))); editor.view.focus() }
const selectToc = editor => { const item = nodes(editor, "tableOfContents")[0]; assert(item, "缺少目录"); editor.view.dispatch(editor.state.tr.setSelection(NodeSelection.create(editor.state.doc, item.pos))); return item }
const setInput = (element, value) => { assert(element instanceof HTMLInputElement, "导航字段不存在"); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value").set.call(element, String(value)); element.dispatchEvent(new Event("input", { bubbles: true })) }
const setSelect = (element, value) => { assert(element instanceof HTMLSelectElement, "导航下拉不存在"); element.value = String(value); element.dispatchEvent(new Event("change", { bubbles: true })) }
const linkMarks = editor => { const found = []; editor.state.doc.descendants((node, pos) => { if (node.isText) for (const mark of node.marks) if (mark.type.name === "link") found.push({ text: node.text, pos, attrs: mark.attrs }) }); return found }
function Probe({ onContext }) { const context = useDocumentEditor(); useEffect(() => { if (context.editor) onContext(context) }, [context, onContext]); return <EditorWorkspace onDocumentChange={() => {}} /> }

/** 隔离随机文档 ID 并排空保存后清理，恢复模式与格式标记偏好；不触碰用户 4177 正文。 */
export async function runNavigationChecks(report = () => {}) {
  const preferences = new Map([TOOLBAR_MODE_KEY, FORMATTING_MARKS_KEY].map(key => [key, localStorage.getItem(key)]))
  const records = new Map()
  const host = document.createElement("div")
  host.style.cssText = "position:relative;width:1280px;max-width:100%;height:900px;margin:24px 0"
  document.body.append(host)
  let current
  const toolbar = () => host.querySelector("[data-toolbar-mode]")
  const panel = () => [...host.querySelectorAll('[role="tabpanel"]')].find(visible)
  const menuItem = name => [...document.querySelectorAll('[role="menuitemradio"]')].find(element => visible(element) && element.textContent === name)
  const mode = async value => { if (toolbar().dataset.toolbarMode === value) return; button(host, "切换工具栏").click(); const label = TOOLBAR_MODES.find(item => item.key === value).label; (await waitFor(() => menuItem(label), "模式菜单未打开")).click(); await waitFor(() => toolbar().dataset.toolbarMode === value && !menuItem(label), "模式未切换") }
  const insertPanel = async () => { current.store.getState().updateView({ activeTab: "插入" }); return waitFor(() => panel()?.getAttribute("aria-label") === "插入工具" && panel(), "插入组未显示") }
  const unmount = async () => { if (current?.editor && !current.editor.isDestroyed) await current.saveDocument(); ReactDOM.unmountComponentAtNode(host); current = null; await delay() }
  const mount = async record => {
    await unmount(); localStorage.removeItem(TOOLBAR_MODE_KEY); localStorage.setItem(FORMATTING_MARKS_KEY, "false")
    if (!record) { const document = { ...createDocument(), title: `导航验收-${Date.now()}-${Math.random().toString(16).slice(2, 8)}`, content: fixture() }; const assets = new Map(); const saved = await saveLocalDocument(document, assets, 0); record = { document, assets, storageVersion: saved.storageVersion }; records.set(document.id, { document, assets }) }
    ReactDOM.render(<EditorProvider record={record}><Probe onContext={context => { current = context }} /></EditorProvider>, host)
    await waitFor(() => current?.editor && current.documentId === record.document.id && toolbar(), "导航 Workspace 未就绪")
    current.store.getState().updateView({ activeTab: "插入", outlineOpen: false, fitWidth: false, zoom: 1 }); await insertPanel(); return current
  }
  const put = async (name, field, value) => { setInput(dialog(name)?.querySelector(`[aria-label="${field}"]`), value); await delay() }
  const close = async name => { button(dialog(name), name === "书签" ? "关闭" : "取消").click(); await waitFor(() => !dialog(name), `${name}未关闭`) }
  const apply = async (name, label) => { const trigger = button(dialog(name), label); assert(trigger && !trigger.disabled, `${label}不可用`); trigger.click(); await waitFor(() => !dialog(name), `${label}没有成功关闭弹窗`) }
  const openToc = async () => { await insertPanel(); (await waitFor(() => button(panel(), "插入目录")?.disabled === false && button(panel(), "插入目录"), "目录插入不可用")).click(); return waitFor(() => dialog("插入目录"), "目录表单未打开") }
  const openTocSettings = async () => { selectToc(current.editor); await insertPanel(); (await waitFor(() => button(panel(), "目录设置"), "目录设置缺失")).click(); return waitFor(() => dialog("目录设置"), "目录设置未打开") }
  const openBookmarks = async () => { await insertPanel(); button(panel(), "管理书签").click(); return waitFor(() => dialog("书签"), "书签管理未打开") }
  const addBookmark = async (text, name) => { select(current.editor, text); await openBookmarks(); await put("书签", "书签名称", name); button(dialog("书签"), "添加书签").click(); await waitFor(() => listNavigationTargets(current.editor).some(item => item.type === "bookmark" && item.name === name), "书签未添加"); await close("书签") }
  const openLink = async (text = "链接文字原段", from = 1, to = 5) => { select(current.editor, text, from, to); await insertPanel(); (await waitFor(() => button(panel(), "编辑链接")?.disabled === false && button(panel(), "编辑链接"), "链接入口不可用")).click(); return waitFor(() => dialog("编辑链接"), "链接表单未打开") }
  const chooseInternal = async label => { dialog("编辑链接").querySelector('input[aria-label="文档位置"]').click(); await delay(); const select = dialog("编辑链接").querySelector('select[aria-label="链接目标位置"]'); const option = [...select.options].find(item => !item.disabled && item.textContent.includes(label)); assert(option, `缺少目标${label}`); setSelect(select, option.value); await delay() }
  const check = async (name, run) => { try { await mount(); await run(current); report({ name, passed: true }) } catch (error) { report({ name, passed: false, error: error.message }) } finally { await unmount() } }
  try {
    await check("目录：两种模式原光标分段插入并建立稳定标题 ID，一次撤销重做", async ({ editor }) => {
      for (const value of ["ribbon", "compact"]) { await mode(value); editor.commands.setContent(fixture()); select(editor, "前半后半", 3); const before = content(editor); await openToc(); select(editor, "尾部文字"); await apply("插入目录", "确认插入目录"); assert(nodes(editor, "tableOfContents").length === 1 && block(editor, "前半") && block(editor, "后半"), "目录没有保留原位置和两侧文字"); const entries = nodes(editor, "tableOfContents")[0].node.attrs.entries; assert(entries.length === 3 && entries.every(entry => entry.id.startsWith("nav-")), "目录标题级别或稳定目标错误"); const after = content(editor); assert(editor.commands.undo() && content(editor) === before, "目录及标题 ID 没有一次撤销"); assert(editor.commands.redo() && content(editor) === after, "目录及标题 ID 没有一次重做") }
    })
    await check("目录：标题改名、新增和删除实时更新，同一输入撤销恢复目录", async ({ editor }) => {
      select(editor, "前半后半"); await openToc(); await apply("插入目录", "确认插入目录"); const before = content(editor); const chapter = block(editor, "第二章"); const id = chapter.node.attrs.navigationId; editor.view.dispatch(closeHistory(editor.state.tr)); editor.commands.insertContentAt(chapter.pos + 1, "新版"); editor.view.dispatch(closeHistory(editor.state.tr)); assert(nodes(editor, "tableOfContents")[0].node.attrs.entries.some(item => item.id === id && item.text === "新版第二章"), "改名未刷新同 ID 目录"); assert(editor.commands.undo() && content(editor) === before, "改名与自动目录不在同一次撤销"); editor.commands.insertContentAt(editor.state.doc.content.size, heading("新增章", 2)); assert(nodes(editor, "tableOfContents")[0].node.attrs.entries.some(item => item.text === "新增章"), "新增标题没有目录条目"); const added = block(editor, "新增章"); editor.view.dispatch(editor.state.tr.delete(added.pos, added.pos + added.node.nodeSize)); assert(!nodes(editor, "tableOfContents")[0].node.attrs.entries.some(item => item.text === "新增章"), "删除标题仍残留目录条目")
    })
    await check("目录设置：标题校验、级别筛选、手动更新无冗余修订及删除撤销", async ({ editor, store }) => {
      select(editor, "前半后半"); await openToc(); await apply("插入目录", "确认插入目录"); await openTocSettings(); const before = content(editor); await put("目录设置", "目录标题", " "); dialog("目录设置").querySelector("form").dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })); await delay(); assert(content(editor) === before && dialog("目录设置").querySelector('[role="alert"]'), "空目录标题被接受"); await put("目录设置", "目录标题", "章节导航"); setSelect(dialog("目录设置").querySelector('select[aria-label="最大标题级别"]'), 4); await delay(); await apply("目录设置", "应用目录设置"); assert(nodes(editor, "tableOfContents")[0].node.attrs.entries.length === 4 && editor.view.dom.querySelector("[data-toc-title]").textContent === "章节导航", "目录设置未真实渲染"); selectToc(editor); const revision = store.getState().revision; const snapshot = content(editor); assert(refreshTableOfContents(editor, captureTableOfContentsTarget(editor)).ok && content(editor) === snapshot && store.getState().revision === revision, "重复更新制造修订"); await insertPanel(); button(panel(), "删除目录").click(); assert(!nodes(editor, "tableOfContents").length && editor.commands.undo() && content(editor) === snapshot, "目录删除不可一次撤销")
    })
    await check("目录设置：原目标映射与跨模式草稿，未改字段保留并发属性", async ({ editor }) => {
      select(editor, "前半后半"); await openToc(); await apply("插入目录", "确认插入目录"); await openTocSettings(); setSelect(dialog("目录设置").querySelector('select[aria-label="最大标题级别"]'), 4); await delay(); const toc = nodes(editor, "tableOfContents")[0]; editor.view.dispatch(editor.state.tr.setNodeAttribute(toc.pos, "title", "并发标题")); editor.commands.insertContentAt(block(editor, "尾部文字").pos + 1, "新增文字", { updateSelection: false }); select(editor, "第一章"); await mode("compact"); current.store.getState().updateView({ activeTab: "视图" }); await apply("目录设置", "应用目录设置"); assert(nodes(editor, "tableOfContents")[0].node.attrs.title === "并发标题" && nodes(editor, "tableOfContents")[0].node.attrs.maxLevel === 4, "目录草稿漂移或覆盖未改字段")
    })
    await check("目录设置：相邻目录的原目标删除后拒绝旧草稿，不误写移动来的目录", async ({ editor }) => {
      select(editor, "前半后半"); await openToc(); await put("插入目录", "目录标题", "第一目录"); await apply("插入目录", "确认插入目录"); const first = nodes(editor, "tableOfContents")[0]; editor.commands.insertContentAt(first.pos + first.node.nodeSize, { type: "tableOfContents", attrs: { ...first.node.attrs, title: "第二目录" } }); assert(nodes(editor, "tableOfContents").length === 2, "未建立相邻目录"); await openTocSettings(); await put("目录设置", "目录标题", "不应写入相邻目录"); assert(removeTableOfContents(editor, captureTableOfContentsTarget(editor)).ok, "原目录删除失败"); const afterDeletion = content(editor); dialog("目录设置").querySelector("form").dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })); await delay(); assert(content(editor) === afterDeletion && nodes(editor, "tableOfContents")[0].node.attrs.title === "第二目录" && dialog("目录设置").querySelector('[role="alert"]'), "原设置草稿误写了移动到同位置的相邻目录"); await close("目录设置")
    })
    await check("目录：部分文字和单元格源禁用，原插入段删除后旧草稿拒绝", async ({ editor }) => {
      select(editor, "链接文字原段", 1, 3); await insertPanel(); await waitFor(() => button(panel(), "插入目录").disabled, "部分文字仍允许目录插入"); editor.commands.insertContentAt(editor.state.doc.content.size, { type: "table", content: [{ type: "tableRow", content: [{ type: "tableCell", content: [paragraph("格内目录源")] }] }] }); select(editor, "格内目录源"); await insertPanel(); assert(button(panel(), "插入目录").disabled, "单元格仍允许目录插入"); select(editor, "链接文字原段"); await openToc(); const source = block(editor, "链接文字原段"); editor.view.dispatch(closeHistory(editor.state.tr.delete(source.pos, source.pos + source.node.nodeSize))); editor.view.dispatch(closeHistory(editor.state.tr)); editor.commands.undo(); const before = content(editor); dialog("插入目录").querySelector("form").dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })); await delay(); assert(content(editor) === before && dialog("插入目录").querySelector('[role="alert"]'), "删除后撤销复活了旧目录插入草稿"); await close("插入目录")
    })
    await check("书签：绑定原段落、名称校验、重命名和删除保留正文且独立撤销", async ({ editor }) => {
      select(editor, "链接文字原段"); await openBookmarks(); const before = content(editor); await put("书签", "书签名称", " "); button(dialog("书签"), "添加书签").click(); await delay(); assert(content(editor) === before && dialog("书签").querySelector('[role="alert"]'), "空书签名称被接受"); await put("书签", "书签名称", "原段书签"); editor.commands.insertContentAt(1, "前方新字", { updateSelection: false }); select(editor, "尾部文字"); button(dialog("书签"), "添加书签").click(); await waitFor(() => listNavigationTargets(editor).some(item => item.name === "原段书签"), "书签未命中原段"); const entry = listNavigationTargets(editor).find(item => item.name === "原段书签"); assert(entry.text === "链接文字原段", "书签跟随后改光标"); button(dialog("书签"), "重命名书签：原段书签").click(); await put("书签", "重命名书签", "更名书签"); button(dialog("书签"), "保存书签名称").click(); await waitFor(() => listNavigationTargets(editor).some(item => item.name === "更名书签" && item.id === entry.id), "重命名改变了书签身份"); const named = content(editor); const text = editor.getText(); button(dialog("书签"), "删除书签：更名书签").click(); await waitFor(() => !listNavigationTargets(editor).some(item => item.name === "更名书签"), "删除书签未生效"); assert(editor.getText() === text && editor.commands.undo() && content(editor) === named, "删书签改字或不可单次撤销"); await close("书签")
    })
    await check("书签重命名：原节点删除和撤销恢复不复活草稿", async ({ editor }) => {
      await addBookmark("链接文字原段", "会删除的书签"); await openBookmarks(); button(dialog("书签"), "重命名书签：会删除的书签").click(); await put("书签", "重命名书签", "不应应用"); const item = block(editor, "链接文字原段"); editor.view.dispatch(closeHistory(editor.state.tr.delete(item.pos, item.pos + item.node.nodeSize))); editor.view.dispatch(closeHistory(editor.state.tr)); editor.commands.undo(); const before = content(editor); const form = dialog("书签").querySelector('input[aria-label="重命名书签"]').closest("form"); form.dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })); await delay(); assert(content(editor) === before && dialog("书签").querySelector('[role="alert"]'), "旧重命名草稿写入撤销恢复的新目标"); await close("书签")
    })
    await check("内部链接：新标题 ID 与原文字链接一次撤销，光标内修改扩展整条已有链接", async ({ editor }) => {
      const before = content(editor); await openLink(); await chooseInternal("第一章"); await apply("编辑链接", "应用链接"); const headingId = block(editor, "第一章").node.attrs.navigationId; assert(linkMarks(editor).some(item => item.text === "链接文字" && item.attrs.href === `#${headingId}` && item.attrs.target === "_self"), "内部链接没有写入原文字或_self目标"); const after = content(editor); assert(editor.commands.undo() && content(editor) === before, "标题 ID 与内部链接分成两次撤销"); assert(editor.commands.redo() && content(editor) === after, "内部链接重做丢失标题身份"); await addBookmark("书签目标正文", "补充位置"); await openLink("链接文字原段", 3, 3); await chooseInternal("补充位置"); await apply("编辑链接", "应用链接"); const id = listNavigationTargets(editor).find(item => item.name === "补充位置").id; assert(linkMarks(editor).filter(item => item.attrs.href === `#${id}`).map(item => item.text).join("") === "链接文字", "光标内修改只改一个字符或误扩展后来选区")
    })
    await check("内部链接：目的段或原文字删除后拒绝旧弹窗，缺失目标显示错误", async ({ editor }) => {
      for (const text of ["第一章", "链接文字原段"]) { editor.commands.setContent(fixture()); await openLink(); await chooseInternal("第一章"); const item = block(editor, text); editor.view.dispatch(closeHistory(editor.state.tr.delete(item.pos, item.pos + item.node.nodeSize))); editor.view.dispatch(closeHistory(editor.state.tr)); editor.commands.undo(); const before = content(editor); button(dialog("编辑链接"), "应用链接").click(); await delay(); assert(content(editor) === before && dialog("编辑链接").querySelector('[role="alert"]'), `${text}删除后复活了旧链接目标`); await close("编辑链接") }
    })
    await check("外部链接：旧默认入口、安全地址校验、原选区恢复和光标移除保留其他文字", async ({ editor }) => {
      await openLink(); assert(dialog("编辑链接").querySelector('input[aria-label="外部地址"]').checked, "外部链接不是旧默认类型"); await put("编辑链接", "链接地址", "javascript:alert(1)"); button(dialog("编辑链接"), "应用链接").click(); await waitFor(() => dialog("编辑链接").querySelector(".ant-form-item-explain-error"), "不安全外链没有表单错误"); await put("编辑链接", "链接地址", "https://example.com/reference"); select(editor, "尾部文字"); await apply("编辑链接", "应用链接"); assert(linkMarks(editor).some(item => item.text === "链接文字" && item.attrs.href === "https://example.com/reference"), "外链没有保留原选区"); await openLink("链接文字原段", 3, 3); button(dialog("编辑链接"), "移除链接").click(); await waitFor(() => !dialog("编辑链接"), "链接移除未关闭"); assert(!linkMarks(editor).length && block(editor, "尾部文字").node.textContent === "尾部文字", "移除链接改变了正文")
    })
    await check("书签与文内导航：只读可管理定位，折叠正文自动展开且正文/修订不变", async ({ editor, store }) => {
      await addBookmark("书签目标正文", "只读位置"); await openLink(); await chooseInternal("只读位置"); await apply("编辑链接", "应用链接"); const before = content(editor); const revision = store.getState().revision; const details = editor.view.dom.querySelector("[data-details-view]"); details.querySelector("[data-details-toggle]").click(); store.getState().updateView({ readOnly: true }); await waitFor(() => !editor.isEditable, "只读未生效"); await openBookmarks(); assert(button(dialog("书签"), "添加书签").disabled && button(dialog("书签"), "删除书签：只读位置").disabled, "只读允许写入书签"); button(dialog("书签"), "定位书签：只读位置").click(); assert(details.dataset.expanded === "true" && editor.state.selection.from === block(editor, "书签目标正文").pos + 1, "只读定位没有进入折叠正文"); await close("书签"); assert(content(editor) === before && store.getState().revision === revision, "只读定位修改文档")
    })
    await check("文内链接：只读普通 DOM 点击阻止页面导航并展开详情，正文和更新计数不变", async ({ editor, store }) => {
      await addBookmark("书签目标正文", "点击位置"); await openLink(); await chooseInternal("点击位置"); await apply("编辑链接", "应用链接"); const id = listNavigationTargets(editor).find(item => item.name === "点击位置").id; const anchor = editor.view.dom.querySelector(`a[href="#${id}"]`); assert(anchor, "正文内部链接不存在"); const details = editor.view.dom.querySelector("[data-details-view]"); if (details.dataset.expanded !== "false") details.querySelector("[data-details-toggle]").click(); store.getState().updateView({ readOnly: true }); await waitFor(() => !editor.isEditable, "只读点击场景未进入只读"); const before = content(editor); const revision = store.getState().revision; const url = window.location.href; let updates = 0; const onUpdate = () => { updates++ }; editor.on("update", onUpdate); try { const event = new MouseEvent("click", { bubbles: true, cancelable: true, button: 0 }); const allowed = anchor.dispatchEvent(event); assert(!allowed && event.defaultPrevented, "只读文内点击未阻止浏览器默认跳转"); await waitFor(() => editor.state.selection.from === block(editor, "书签目标正文").pos + 1 && details.dataset.expanded === "true", "只读普通点击未定位并展开折叠详情"); assert(content(editor) === before && store.getState().revision === revision && updates === 0 && window.location.href === url, "只读文内点击改写正文、修订或页面地址") } finally { editor.off("update", onUpdate) }
    })
    await check("导航写入：只读、文档切换和输入法组合期间拒绝命令与表单提交", async ({ editor, store }) => {
      for (const reason of ["readOnly", "switching", "composition"]) { select(editor, "链接文字原段"); const bookmark = captureNavigationBlockTarget(editor); const source = captureNavigationLinkTarget(editor); const destination = captureNavigationBlockTarget(editor, block(editor, "第一章").pos); const insertion = captureNavigationInsertTarget(editor); const before = content(editor); if (reason === "composition") editor.view.dom.dispatchEvent(new CompositionEvent("compositionstart", { bubbles: true })); else store.getState().updateView({ [reason]: true }); await waitFor(() => reason === "composition" ? editor.view.composing : !editor.isEditable, "禁写状态未生效"); const blocked = store.getState().readOnly || store.getState().switching; assert(!setBookmarkName(editor, bookmark, "不允许的名称", blocked).ok && !insertTableOfContentsAtTarget(editor, insertion, { title: "目录", maxLevel: 3 }, blocked).ok && !applyInternalNavigationLink(editor, source, destination, blocked).ok && content(editor) === before, `${reason}允许导航写入`); if (reason === "composition") { editor.view.dom.dispatchEvent(new CompositionEvent("compositionend", { bubbles: true })); await waitFor(() => !editor.view.composing, "组合输入未结束") } else { store.getState().updateView({ [reason]: false }); await waitFor(() => editor.isEditable, "恢复编辑失败") } }
      select(editor, "前半后半"); await openToc(); await put("插入目录", "目录标题", "恢复后的目录"); store.getState().updateView({ readOnly: true }); await waitFor(() => button(dialog("插入目录"), "确认插入目录").disabled, "目录草稿未禁写"); const before = content(editor); dialog("插入目录").querySelector("form").dispatchEvent(new Event("submit", { bubbles: true, cancelable: true })); await delay(); assert(content(editor) === before && dialog("插入目录").querySelector('input[aria-label="目录标题"]').value === "恢复后的目录", "禁写时目录草稿丢失或改正文"); store.getState().updateView({ readOnly: false }); await waitFor(() => !button(dialog("插入目录"), "确认插入目录").disabled, "恢复目录提交失败"); await apply("插入目录", "确认插入目录")
    })
    await check("导航：保存同 ID 重开及 Mewoc 往返保留稳定锚点、书签、目录和内部地址", async context => {
      await addBookmark("书签目标正文", "持久位置"); select(context.editor, "前半后半"); await openToc(); await apply("插入目录", "确认插入目录"); await openLink(); await chooseInternal("持久位置"); await apply("编辑链接", "应用链接"); assert(await context.saveDocument(), "导航保存失败"); const expected = content(context.editor); const record = await getLocalDocument(context.documentId); const reopened = await mount({ ...record, assets: new Map() }); assert(content(reopened.editor) === expected && !reopened.editor.can().undo(), "保存重开丢导航数据或沿用撤销栈"); const portable = await createPortableFile(reopened.getSnapshot(), reopened.assets); const imported = await readPortableFile(new File([JSON.stringify(portable)], "navigation.mewoc.json")); assert(JSON.stringify(imported.document.content) === expected, "Mewoc 往返丢失导航属性")
    })
    await check("导航：离线 HTML 保留可用锚点和目录，真实 Provider 同文档粘贴重映射副本身份", async context => {
      await addBookmark("书签目标正文", "副本位置"); select(context.editor, "前半后半"); await openToc(); await apply("插入目录", "确认插入目录"); await openLink(); await chooseInternal("副本位置"); await apply("编辑链接", "应用链接"); const before = content(context.editor); const original = listNavigationTargets(context.editor); let transformed = context.editor.getHTML(); context.editor.view.someProp("transformPastedHTML", transform => { transformed = transform(transformed, context.editor.view) }); const parsed = new DOMParser().parseFromString(transformed, "text/html"); const copiedTargets = [...parsed.querySelectorAll("[data-navigation-id]")]; assert(copiedTargets.length && copiedTargets.every(element => !original.some(item => item.id === element.dataset.navigationId)), "真实 Provider 同文档粘贴保留冲突 ID"); const copiedBookmark = parsed.querySelector("[data-bookmark-name]"); assert(copiedBookmark?.dataset.bookmarkName.includes("副本") && parsed.querySelector(`a[href="#${copiedBookmark.dataset.navigationId}"]`), "复制内部链接未指向副本书签"); const copiedEntries = JSON.parse(parsed.querySelector('[data-type="table-of-contents"]').dataset.entries); assert(copiedEntries.every(entry => copiedTargets.some(element => element.dataset.navigationId === entry.id)), "副本目录仍指向原文标题"); const temporary = new Editor({ element: document.createElement("div"), extensions: createExtensions(), content: transformed }); try { assert(nodes(temporary, "tableOfContents").length === 1 && linkMarks(temporary).some(item => item.attrs.href === `#${copiedBookmark.dataset.navigationId}`), "清理后的复制 HTML 不能解析为导航节点") } finally { temporary.destroy() }
      const frame = document.createElement("iframe"); frame.style.cssText = "width:700px;height:600px;border:0"; host.append(frame); try { frame.srcdoc = await createDocumentHtml(context.getSnapshot(), context.assets); const document = await waitFor(() => frame.contentDocument?.querySelector('[data-type="table-of-contents"]') && frame.contentDocument, "离线 HTML 未载入目录"); const toc = document.querySelector('[data-type="table-of-contents"]'); const links = [...toc.querySelectorAll("a[href]")]; assert(links.length === 3 && links.every(link => document.getElementById(link.getAttribute("href").slice(1))), "离线目录链接没有真实目标锚点"); assert(frame.contentWindow.getComputedStyle(toc).borderTopWidth !== "0px" && !document.querySelector("[data-toc-view]"), "离线目录缺少外观或携带编辑 NodeView"); assert(content(context.editor) === before, "导出或复制变更源导航数据") } finally { frame.remove() }
    })
  } finally { await unmount(); host.remove(); await removeVerificationDocuments([...records.values()]); for (const [key, value] of preferences) { if (value === null) localStorage.removeItem(key); else localStorage.setItem(key, value) } }
}
